# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
test:
  image: registry.gitlab.com/restbeast/cli-build-image-ci:latest
  only:
  - branches
  script:
  - make test
release:
  image: registry.gitlab.com/restbeast/cli-build-image-ci:latest
  script:
  - make release
  only:
  - tags
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
